In [ ]:
# ↓ここにコードを記入してください
# 問1：NumPy配列の作成
# 0から9までの整数を要素に持つ1次元ndarrayを作成し、出力してください。
import numpy as np

arr = np.linspace(0,9,10)

print(arr)


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [13]:
# ↓ここにコードを記入してください
# 問2：2次元配列の作成
# 3行3列のndarrayを、0から8までの整数で埋めて作成してください。

arr2 = np.array(([0,1,2],[3,4,5],[6,7,8]))

print(arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
# ↓ここにコードを記入してください
# 問3：データ型の確認
# 上記の配列のデータ型（dtype）を確認して表示してください。

print(arr2.dtype)

int64


In [25]:
# ↓ここにコードを記入してください
# 問4：ユニバーサル関数の使用
# 0からπまでを0.1刻みで生成した配列にsin関数を適用し、結果を出力してください。


arr3 = np.arange(0, np.pi ,0.1)
arr4 = np.sign(arr3)
print(arr4)

[0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1.]


In [27]:
# ↓ここにコードを記入してください
# 問5：要素の条件抽出
# 0～20の整数からなる配列を作成し、偶数の要素だけを抽出して表示してください。

arr4 = np.arange(0,20)

print(np.where(arr4 % 2 == 0))



(array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]),)


In [34]:
# ↓ここにコードを記入してください
# 問6：配列のブロードキャスト
# shape (3,1) と shape (1,4) の配列を足し算し、結果を出力してください。

arr5 = np.array([[1],[2],[3]])
arr6 = np.array([[4,5,6,7]])

print(arr5.shape)
print(arr6.shape)

print(arr5+arr6)

(3, 1)
(1, 4)
[[ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]]


In [41]:
# ↓ここにコードを記入してください
# 問7：配列のスライスとコピー
# 1次元配列からスライスした部分配列を変更しても元の配列に影響がないようにしてください。

arr7 = np.arange(10)

arr8 = np.copy(arr7[3:5])

arr8[:] = 64

print(arr7)
print(arr8)

[0 1 2 3 4 5 6 7 8 9]
[64 64]


In [42]:
# ↓ここにコードを記入してください
# 問8：配列の軸方向の合計
# shape (3,3) の配列を作成し、axis=0 と axis=1 での合計をそれぞれ表示してください。

arr9 = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(np.sum(arr9, axis=0))
print(np.sum(arr9, axis=1))


[12 15 18]
[ 6 15 24]


In [46]:
# ↓ここにコードを記入してください
# 問9：ブールインデックスの利用
# 任意の5×5配列を作成し、10より大きい要素だけを抽出してください。

arr10 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,110],[1,2,3,4,5]])

arr11 = arr10[arr10 > 10]

print(arr11)

[ 11  12  13  14  15  16  17  18  19 110]


In [48]:
# ↓ここにコードを記入してください
# 問10：Fancy Indexで要素抽出
# 任意の1次元配列から、[2, 4, 6] 番目の要素を抽出してください。

arr12 = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr12[[2,4,6]])

[3 5 7]


In [66]:
# ↓ここにコードを記入してください
# 問11：where関数の利用
# ランダムな10個の整数の配列を作成し、0以上の要素はそのまま、負の要素は0に変換した配列を作成してください。

arr13 = np.random.standard_normal(size=10)
print(arr13)
arr13 = np.where(arr13 < 0, 0,arr13)
print(arr13)

[-2.02859611  1.4814767   0.2645628   0.56291997 -0.15664535  0.10740438
 -1.16894858  0.77954732  0.98146101 -0.05156785]
[0.         1.4814767  0.2645628  0.56291997 0.         0.10740438
 0.         0.77954732 0.98146101 0.        ]


In [68]:
# ↓ここにコードを記入してください
# 問12：転置とreshape
# shape (2,6) の配列を作成し、shape (3,4) に reshape した後に転置してください。

arr14 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(arr14)

arr14 = arr14.reshape(3,4)

print(arr14)

arr14 = arr14.T

print(arr14)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [69]:
# ↓ここにコードを記入してください
# 問13：平均・中央値・標準偏差
# 任意の配列に対して mean, median, std を計算してください。

arr14_mean = np.mean(arr14)
arr14_median = np.median(arr14)
arr14_std = np.std(arr14)

print(arr14_mean)
print(arr14_median)
print(arr14_std)

6.5
6.5
3.452052529534663


In [ ]:
# ↓ここにコードを記入してください
# 問14：np.argsortの利用
# ランダムな10個の整数の配列を昇順にソートし、そのソート順のインデックスを表示してください。

#わかりません！


[ 0.45587491  1.0239144  -1.02320539  0.52969766 -1.77470536 -0.51201746
  1.44615873  0.62622539 -1.83977983 -0.40950031]


In [71]:
# ↓ここにコードを記入してください
# 問15：ブール配列の作成
# 任意の配列に対して、10より大きいかどうかを判定するブール配列を作成してください。

arr15 = np.array([10,5,3,78,123,1,5,79,12,0])
arr15_bool = arr15 > 10
print(arr15)
print(arr15_bool)

[ 10   5   3  78 123   1   5  79  12   0]
[False False False  True  True False False  True  True False]


In [72]:
# ↓ここにコードを記入してください
# 問16：np.uniqueの利用
# 重複を含む1次元配列を作成し、ユニークな要素だけを取得してください。

arr16 = np.array([1,2,2,2,4,65,7,4,24,35,2431,3,56,1,65,1])

arr16_uni = np.unique(arr16)

print(arr16)
print(arr16_uni)

[   1    2    2    2    4   65    7    4   24   35 2431    3   56    1
   65    1]
[   1    2    3    4    7   24   35   56   65 2431]


In [74]:
# ↓ここにコードを記入してください
# 問17：ndarrayの演算
# 任意の2つの同じshapeの配列を作成し、加算・減算・乗算を行ってください。

arr17_1 = np.random.standard_normal(size=15).reshape(3,5)
arr17_2 = np.random.standard_normal(size=15).reshape(3,5)

print(arr17_1)
print(arr17_2)

print(arr17_1 + arr17_2)
print(arr17_1 - arr17_2)
print(arr17_1 * arr17_2)


[[ 0.37772147 -1.06928078  0.23380512 -2.20106613  0.03765673]
 [-0.73485311 -0.88750983 -0.85267199 -0.25917273  0.23117293]
 [ 1.15612198  1.76596308 -0.5083501   0.13281773 -0.16024591]]
[[-0.98827867 -0.75724152 -0.86184329 -0.16348749 -1.58120042]
 [ 0.89107961 -1.42658037  0.5538194  -2.76865659  1.07619749]
 [ 0.8634787  -2.04690008  0.45683853  1.94870597  0.21738019]]
[[-0.6105572  -1.8265223  -0.62803817 -2.36455361 -1.5435437 ]
 [ 0.1562265  -2.3140902  -0.29885259 -3.02782931  1.30737042]
 [ 2.01960068 -0.280937   -0.05151157  2.0815237   0.05713428]]
[[ 1.36600015 -0.31203926  1.09564842 -2.03757864  1.61885715]
 [-1.62593272  0.53907054 -1.40649139  2.50948386 -0.84502456]
 [ 0.29264329  3.81286316 -0.96518863 -1.81588824 -0.3776261 ]]
[[-0.37329408  0.80970381 -0.20150338  0.35984677 -0.05954283]
 [-0.65481263  1.2661041  -0.47222629  0.71756028  0.24878773]
 [ 0.99828671 -3.61474997 -0.23223391  0.2588227  -0.03483429]]


In [79]:
# ↓ここにコードを記入してください
# 問18：axisを指定した最大値
# shape (4,5) の配列に対して、axis=1 方向の最大値を取得してください。
arr18 = np.random.standard_normal(size=20).reshape(4,5)

print(np.max(arr18,axis=1))

[1.24181242 0.33809702 0.37607867 0.02880582]


In [91]:
# ↓ここにコードを記入してください
# 問19：ndarrayの要素置換
# 任意の配列において、5未満の値を0に、それ以外を1に変換した配列を作成してください。

arr19 = np.arange(20).reshape(4,5)

arr19_5 = np.where(arr19 < 5, 0,1)

print(arr19)
print(arr19_5)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[0 0 0 0 0]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [93]:
# ↓ここにコードを記入してください
# 問20：ndarrayのflatten
# shape (3,3) の配列を作成し、1次元に変換してください。

arr20 = np.arange(9).reshape(3,3)
arr20_fla = arr20.flatten()

print(arr20)
print(arr20_fla)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]
