In [2]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

%timeit my_arr2 = my_arr * 2

%timeit my_list2 = [x * 2 for x in my_list]

1.46 ms ± 39.7 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
32.9 ms ± 178 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [7]:
import numpy as np
data = np.array([[1.5,-0.1,3],[0,-3,6.5]])

print(data)
print(data + data)
print(data * 10)
print(data.shape)
print(data.dtype)


[[ 1.5 -0.1  3. ]
 [ 0.  -3.   6.5]]
[[ 3.  -0.2  6. ]
 [ 0.  -6.  13. ]]
[[ 15.  -1.  30.]
 [  0. -30.  65.]]
(2, 3)
float64


In [ ]:
data1 = [6, 7.5 , 8 , 0, 1]
arr1 = np.array(data1)
arr1
#print(arr1)

array([6. , 7.5, 8. , 0. , 1. ])

In [16]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2
#print(arr2)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.empty((2,3,2)) #これは必ず0が入るわけではない。

array([[[9.28826599e-312, 9.28826599e-312],
        [9.28826599e-312, 1.26974871e-321],
        [7.56571287e-307, 5.74084271e+169]],

       [[6.20516042e-091, 1.65847382e-076],
        [2.82923033e-033, 9.05274525e-043],
        [3.99910963e+252, 1.46030983e-319]]])

In [21]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
arr = np.array([1,2,3,4,5])

print(arr.dtype)

float_arr = arr.astype(np.float64)

print(float_arr.dtype)

arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

print(arr.astype(np.int32))

int64
float64
[ 3 -1 -2  0 12 10]


In [28]:
arr = np.array([[1.,2.,3.],[4.,5.,6]])

arr2 = np.array([[1.,2.,3.],[4.,10.,6]])

print(arr2 > arr)

[[False False False]
 [False  True False]]


In [33]:
list1 = [1,2,3,4,5,6]
list2 = np.array([1,2,3,4,5,6])

list1[1] = 10
list2[1] = 10

print(list1, list2)

#list1[2:4] = 100 #できない！
list2[2:4] = 100
print(list1,list2)

[1, 10, 3, 4, 5, 6] [ 1 10  3  4  5  6]
[1, 10, 3, 4, 5, 6] [  1  10 100 100   5   6]


In [37]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

arr2d[2]
print(arr2d[0][2])
print(arr2d[0,2])

3
3


In [51]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d
#print(arr3d[0])

old_values = arr3d[0].copy()
arr3d[0] = 42

print(arr3d)

#print(old_values)

arr3d[0] = old_values

print(arr3d)

print(arr3d[1,0])

[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[7 8 9]


In [55]:
arr[:1]

array([[1., 2., 3.]])

In [59]:
names = np.array(["Bob","Joe","Will","Bob","Will","Joe","Joe"])

data = np.array([[4,7],[0,2],[5,6],[0,0],[1,2],[-12,-4],[3,4]])

print(data[names == "Bob"])
print(data[names == "Bob", 1])
print(data[names == "Bob", 1:])



[[4 7]
 [0 0]]
[7 0]
[[7]
 [0]]


In [61]:
arr = np.zeros((8,4))
for i in range(8):
    arr[i] = i

arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [63]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [65]:
arr4 = np.arange(15).reshape((3,5))
print(arr4)
print(arr4.T)
print(arr4)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
